version: '3'

volumes:
  mariadb:
  mongodb:
  redis:

services:
  mariadb:
    image: bitnami/mariadb:10.6
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=development
      - MARIADB_USER=app
      - MARIADB_PASSWORD=development
      - MARIADB_DATABASE=app
    volumes:
      - mariadb:/bitnami/mariadb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  redis:
    image: bitnami/redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=development
    volumes:
      - redis:/bitnami/redis/data